objs-y	+= 	context.o
objs-y	+= 	dump-stack.o
objs-y	+= 	init.o
objs-y	+= 	startup.o
objs-y	+= 	switch_to.o
objs-y	+= 	traps.o
objs-y	+= 	vectors.o


deps-y	:= \
	target.lds	\

subdirs-y			+= debug/

subdirs-y			+= socs/

subdirs-$(CONFIG_MACH_CI20)	+= mach-ci20/
