#ifndef	_SOC_CACHE_H_
#define	_SOC_CACHE_H_


#define	CACHE_LI_SET_ORDER	7
#define	CACHE_LI_WAY_ORDER	2
#define	CACHE_LI_SIZ_ORDER	6

#define	CACHE_LI_SETS		(1 << CACHE_LI_SET_ORDER)
#define	CACHE_LI_WAYS		(1 << CACHE_LI_WAY_ORDER)
#define	CACHE_LI_LINESIZE	(1 << CACHE_LI_SIZ_ORDER)


#define	CACHE_LD_SET_ORDER	7
#define	CACHE_LD_WAY_ORDER	2
#define	CACHE_LD_SIZ_ORDER	6

#define	CACHE_LD_SETS		(1 << CACHE_LD_SET_ORDER)
#define	CACHE_LD_WAYS		(1 << CACHE_LD_WAY_ORDER)
#define	CACHE_LD_LINESIZE	(1 << CACHE_LD_SIZ_ORDER)


#define	CACHE_L2_SET_ORDER	9
#define	CACHE_L2_WAY_ORDER	4
#define	CACHE_L2_SIZ_ORDER	6

#define	CACHE_L2_SETS		(1 << CACHE_L2_SET_ORDER)
#define	CACHE_L2_WAYS		(1 << CACHE_L2_WAY_ORDER)
#define	CACHE_L2_LINESIZE	(1 << CACHE_L2_SIZ_ORDER)

// LoUIS: L2
// LoC:	  L2
// LoUU:  L2

#endif
