objs-$(CONFIG_SOC_AM335X)	+= am335x.o
objs-$(CONFIG_SOC_IMX6)		+= imx6-gpt.o
objs-$(CONFIG_SOC_JZ4780)	+= jz47xx-timer.o
objs-$(CONFIG_SOC_STM32)	+= stm32-timer.o
objs-$(CONFIG_MIPS_ARCH_TIMER)	+= mips-arch-timer.o
