objs-y += \
	sprng.o


progs-y	:= hello.test
progs-y	+= fastmod10.test
progs-y	+= sysregs.test
progs-y	+= thread.test

progs-y	+= fault-undef.test
progs-y	+= timer.test
progs-y	+= timeout.test
progs-y	+= printf.test
progs-y	+= sqrt.test
