objs-y	+= sprng.o


progs-y	+= bug.test
progs-y	+= bug_on.test
progs-y	+= fastmod10.test
progs-y	+= fault-undef.test
progs-y	+= findbit.test
progs-y	+= hello.test
progs-y	+= loops-per-second.test
progs-y	+= memcpy.test
progs-$(CONFIG_NET)	+= net.test
progs-$(CONFIG_MM_PAGE)	+= page-alloc.test
progs-y	+= printf.test
progs-y	+= sqrt.test
progs-y	+= sema.test
progs-$(CONFIG_SLAB)	+= slab.test
progs-y	+= sysregs.test
progs-y	+= thread.test
progs-y	+= timeout.test
progs-y	+= timer.test
progs-$(CONFIG_UART)		+= uart.test
progs-$(CONFIG_UART)		+= uart-rxbuf.test

progs-$(CONFIG_SMP)	+= lock.test
progs-$(CONFIG_SMP)	+= sema-smp.test
progs-$(CONFIG_SMP)	+= smp.test
