objs-y	+= sprng.o


progs-y	+= fastmod10.test
progs-y	+= fault-undef.test
progs-y	+= hello.test
progs-y	+= printf.test
progs-y	+= sqrt.test
progs-y	+= sysregs.test
progs-y	+= thread.test
progs-y	+= timeout.test
progs-y	+= timer.test
