objs-y	+= clk-core.o
objs-y	+= clk-fixed.o
objs-y	+= clk-mask.o
objs-y	+= clk-mmio.o
objs-y	+= clk-mmio-fixed.o
objs-y	+= clk-mmio-ratio.o
objs-y	+= clk-mux-mmio.o
objs-y	+= clk-ratio.o
objs-y	+= clk-divider.o
objs-y	+= clk-divtable.o

objs-$(CONFIG_SOC_IMX6)		+= imx-pfd.o
objs-$(CONFIG_SOC_IMX6)		+= imx6-pll.o
objs-$(CONFIG_SOC_IMX6SX)	+= imx6sx.o
objs-$(CONFIG_SOC_JZ4780)	+= jz4780.o
objs-$(CONFIG_SOC_STM32)	+= stm32.o
