CROSS_COMPILE	?= arm-linux-

ARCHFLAGS-$(CONFIG_ARMV4T)	+= -march=armv4t
ARCHFLAGS-$(CONFIG_ARM7TDMI)	+= -mtune=arm7tdmi
ARCHFLAGS-$(CONFIG_ARM720T)	+= -mtune=arm7tdmi

ARCHFLAGS-$(CONFIG_ARMV5)	+= -march=armv5
ARCHFLAGS-$(CONFIG_ARMV5T)	+= -march=armv5t
ARCHFLAGS-$(CONFIG_ARMV5TE)	+= -march=armv5te
ARCHFLAGS-$(CONFIG_ARM926)	+= -mtune=arm926tdmi
ARCHFLAGS-$(CONFIG_ARM926EJS)	+= -mtune=arm926ej-s

ARCHFLAGS-$(CONFIG_CORTEX_A8)	+= -march=armv7-a -mcpu=cortex-a8 -mtune=cortex-a8
