objs-y	:= \
	startup.o	\
	switch_to.o	\
	irq.o		\
	context.o	\
	traps.o		\


deps-y	:= \
	target.lds	\


subdirs-y			+= lib/
subdirs-y			+= debug/
subdirs-$(CONFIG_MACH_BEAGLEBONE)	+= mach-beaglebone/
