subdirs-y += init/
subdirs-y += irq/
subdirs-$(CONFIG_SMP) += smp/
subdirs-y += sync/
subdirs-y += time/

objs-y	+= bug.o
objs-y	+= halt.o
objs-y	+= idle.o
objs-y	+= sched.o
objs-y	+= schedule-timeout.o
objs-y	+= thread.o
objs-y	+= undef.o
objs-y	+= waitqueue.o
