objs-$(CONFIG_SOC_AM335X)	+= am335x.o
objs-$(CONFIG_SOC_AR933X)	+= ath79.o
objs-$(CONFIG_SOC_BCM2835)	+= bcm2835.o
objs-$(CONFIG_SOC_JZ4780)	+= jz4780-intc.o
objs-$(CONFIG_ARCH_MIPS)	+= mips-cpu.o
objs-$(CONFIG_MIPS_GIC)		+= mips-gic.o
objs-$(CONFIG_ARMV7M)		+= arm-nvic.o
objs-$(CONFIG_ARM_GIC)		+= arm-gic.o
