#!/bin/sh


do_makefile()
{
	dir="$1"
	out="$2"

	echo "objs-y	:="
	echo "subdirs-y :="
	echo "deps-y :="
	echo
	cat "$dir/Makefile" | \
		sed "s:^EXTRA_CFLAGS[^A_Z_-]:$dir/&:"	| \
		sed "s:^[a-zA-Z0-9_-]*-cflags:$dir/&:"	| \
		sed "s:^EXTRA_AFLAGS[^A_Z_-]:$dir/&:"	| \
		sed "s:^[a-zA-Z0-9_-]*-aflags:$dir/&:"	| \
		sed "s:^EXTRA_CPPFLAGS[^A_Z_-]:$dir/&:"	| \
		sed "s:^[a-zA-Z0-9_-]*-cppflags:$dir/&:"| \
		sed "s:^[a-zA-Z0-9_-]*-objs:$dir/&:"| \
		cat
	echo
	echo "ifneq (\$(objs-y),)"
	echo "objs += \$(objs-y:%=$dir/%)"
	echo "-include \$(objs-y:%=$dir/.%.cmd)"
	echo "endif"
	echo "ifneq (\$(deps-y),)"
	echo "-include \$(deps-y:%=$dir/.%.cmd)"
	echo "endif"
	echo "ifneq (\$(subdirs-y),)"
	echo "-include \$(subdirs-y:%=$dir/%$out)"
	echo "endif"

}

out="$1"
shift

for i in "$@"
do
	dir=${i%/Makefile}
	do_makefile "$dir" "$out" > "$dir/$out"
done
