#!/bin/sh


do_makefile()
{
	dir="$1"

	echo "objs-y	:="
	echo "progs-y	:="
	echo "subdirs-y :="
	echo "deps-y :="
	echo
	cat "$dir/Makefile" | \
		sed "s:^EXTRA_CFLAGS[^A_Z_-]:$dir/&:"	| \
		sed "s:^[a-zA-Z0-9_-]*-cflags:$dir/&:"	| \
		sed "s:^EXTRA_AFLAGS[^A_Z_-]:$dir/&:"	| \
		sed "s:^[a-zA-Z0-9_-]*-aflags:$dir/&:"	| \
		sed "s:^EXTRA_CPPFLAGS[^A_Z_-]:$dir/&:"	| \
		sed "s:^[a-zA-Z0-9_-]*-cppflags:$dir/&:"| \
		sed "s:^[a-zA-Z0-9_-]*-objs:$dir/&:"| \
		cat
	echo
	echo "ifneq (\$(progs-y),)"
	echo "$dir/progs := \$(progs-y:%=$dir/%)"
	echo "$dir/: \$($dir/progs)"
	echo "progs += \$($dir/progs)"
	echo "-include \$(progs-y:%=$dir/.%.o.cmd)"
	echo "-include \$(progs-y:%=$dir/.%.s.cmd)"
	echo "endif"
	echo
	echo "ifneq (\$(objs-y),)"
	echo "-include \$(objs-y:%.o=$dir/.%.o.cmd)"
	echo "-include \$(objs-y:%.o=$dir/.%.s.cmd)"
	echo
	echo "-include $dir/.lib.a.d"
	echo "$dir/lib.a: \$(objs-y:%=$dir/%)"
	echo "libs += $dir/lib.a"
	echo "$dir/: $dir/lib.a"
	echo "endif"
	echo
	echo "# For hierarchical libs:"
	echo "# $dir/lib.a: \$(objs-y:%=$dir/%) \$(subdirs-y:%/=$dir/%/lib.a)"
	echo
	echo "ifneq (\$(deps-y),)"
	echo "-include \$(deps-y:%=$dir/.%.cmd)"
	echo "endif"
	echo "ifneq (\$(subdirs-y),)"
	echo "-include \$(subdirs-y:%/=$dir/%/.make)"
	echo "endif"

}

for dir in "$@"
do
	do_makefile "$dir" > "$dir/.make"
done
