.PHONY: __clean
__clean:

src := $(obj)
clean-files :=
include $(src)/Makefile

clean-files += $(hostprogs-y) $(hostprogs-n) $(hostprogs-)
progs-files := $(progs-y) $(progs-n) $(progs-)
clean-files += $(progs-files) $(progs-files:%=%.map)

clean-files := $(addprefix $(obj)/,$(clean-files))

__clean:
	@echo "CLEAN $(clean-files)"
	@rm -f $(clean-files)
