.PHONY: __clean
__clean:

src := $(obj)
clean-files :=
include $(src)/Makefile

clean-files += $(hostprogs-y) $(hostprogs-n) $(hostprogs-)
progs-files := $(progs-y) $(progs-n) $(progs-)
clean-files += $(progs-files)

files-to-clean := $(clean-files) $(progs-files:%=%.map) $(progs-files:%=%.bin)
files-to-clean := $(addprefix $(obj)/,$(files-to-clean))

__clean:
	@echo "CLEAN	$(obj)/:$(clean-files:%.test=%)"
	@rm -f $(files-to-clean)
