#ifndef	_MEMTESTER_H_
#define	_MEMTESTER_H_


enum {
	MEMTESTER_STUCKAD_BIT,
#define	MEMTESTER_STUCKAD	(1 << MEMTESTER_STUCKAD_BIT)
	MEMTESTER_RANDVAL_BIT,
#define	MEMTESTER_RANDVAL	(1 << MEMTESTER_RANDVAL_BIT)
	MEMTESTER_COMPXOR_BIT,
#define	MEMTESTER_COMPXOR	(1 << MEMTESTER_COMPXOR_BIT)
	MEMTESTER_COMPSUB_BIT,
#define	MEMTESTER_COMPSUB	(1 << MEMTESTER_COMPSUB_BIT)
	MEMTESTER_COMPMUL_BIT,
#define	MEMTESTER_COMPMUL	(1 << MEMTESTER_COMPMUL_BIT)
	MEMTESTER_COMPDIV_BIT,
#define	MEMTESTER_COMPDIV	(1 << MEMTESTER_COMPDIV_BIT)
	MEMTESTER_COMP_OR_BIT,
#define	MEMTESTER_COMP_OR	(1 << MEMTESTER_COMP_OR_BIT)
	MEMTESTER_COMPAND_BIT,
#define	MEMTESTER_COMPAND	(1 << MEMTESTER_COMPAND_BIT)
	MEMTESTER_SEQ_INC_BIT,
#define	MEMTESTER_SEQ_INC	(1 << MEMTESTER_SEQ_INC_BIT)
	MEMTESTER_SOLBITS_BIT,
#define	MEMTESTER_SOLBITS	(1 << MEMTESTER_SOLBITS_BIT)
	MEMTESTER_BLK_SEQ_BIT,
#define	MEMTESTER_BLK_SEQ	(1 << MEMTESTER_BLK_SEQ_BIT)
	MEMTESTER_CHECKER_BIT,
#define	MEMTESTER_CHECKER	(1 << MEMTESTER_CHECKER_BIT)
	MEMTESTER_BIT_SPR_BIT,
#define	MEMTESTER_BIT_SPR	(1 << MEMTESTER_BIT_SPR_BIT)
	MEMTESTER_BITFLIP_BIT,
#define	MEMTESTER_BITFLIP	(1 << MEMTESTER_BITFLIP_BIT)
	MEMTESTER_WALK1_BIT,
#define	MEMTESTER_WALK1		(1 << MEMTESTER_WALK1_BIT)
	MEMTESTER_WALK0_BIT,
#define	MEMTESTER_WALK0		(1 << MEMTESTER_WALK0_BIT)
	MEMTESTER_WRITE8_BIT,
#define	MEMTESTER_WRITE8	(1 << MEMTESTER_WRITE8_BIT)
	MEMTESTER_WRITE16_BIT,
#define	MEMTESTER_WRITE16	(1 << MEMTESTER_WRITE16_BIT)

	MEMTESTER_LAST_BIT,
#define	MEMTESTER_ALL		((1 << MEMTESTER_LAST_BIT) - 1)
};


int memtester(void *buff, ulong size, uint loops, uint testmask);

#endif
